// <auto-generated />
namespace CF_consol_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addFKTodoItemtableandDefaultproterty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFKTodoItemtableandDefaultproterty));
        
        string IMigrationMetadata.Id
        {
            get { return "202103231733316_add FK TodoItem.table and Default proterty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
