//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBF_console_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tanar()
        {
            this.Tantargies = new HashSet<Tantargy>();
        }
    
        public int Id { get; set; }
        public string Nev { get; set; }
        public Nullable<int> SzülAdat { get; set; }
        public string E_mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tantargy> Tantargies { get; set; }
    }
}
