//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBF_console_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tantargy
    {
        public int Id { get; set; }
        public string Tantargyak { get; set; }
        public Nullable<int> Tanarid { get; set; }
    
        public virtual Tanar Tanar { get; set; }
    }
}
