// <auto-generated />
namespace CF_consol_02_gyak.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newtabletipusandpropertychange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newtabletipusandpropertychange));
        
        string IMigrationMetadata.Id
        {
            get { return "202103301517367_new table tipus and property change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
