//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_gyakorlas_DBF_entity_adat_mentese
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanar
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public string Varos { get; set; }
        public string Vegzetseg { get; set; }
        public string Neme { get; set; }
    }
}
